/* eslint-disable multiline-ternary */
/* eslint-disable no-unused-expressions */
/* eslint-disable no-duplicate-imports */
/* eslint-disable no-unused-vars */
import React from 'react'
import { useEffect, Fragment, useState } from 'react'
import { Dropdown, DropdownMenu, DropdownToggle, DropdownItem, Badge, Button, Input } from 'reactstrap'


const FoundItems = (props) => {
    const [dropdownOpen, setDropdownOpen] = useState(false)
    const toggle = () => setDropdownOpen(prevState => !prevState)
    return (
    <Dropdown isOpen={dropdownOpen} toggle={toggle} tag='li' className='dropdown-cart nav-item me-25'>
      <DropdownMenu end tag='ul' className='dropdown-menu-media dropdown-cart mt-0' style={{minWidth:'260px'}}>
        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>

        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>

        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>

        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>        <p>
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        aaaaaaaa
        </p>
      </DropdownMenu>
    </Dropdown>
  )
}

export default FoundItems
