const GraphData = [
    {
        address:"kuft1",
        symbole:"eth",
        inputs:[
            {
                hash:"inp1",
                timeStamp:1223,
                value:1200
            }
        ],
        outputs:[
            {
                hash:"out1",
                timeStamp:3441,
                value:2200
            }
        ]
    },
    {
        address:"kuft2",
        symbole:"eth",
        inputs:[
            {
                hash:"inp2",
                timeStamp:1223,
                value:1200
            }
        ],
        outputs:[
            {
                hash:"inp1",
                timeStamp:3441,
                value:2200
            },
            {
                hash:"out2",
                timeStamp:3441,
                value:2200
            }
        ]
    },
    {
        address:"kuft3",
        symbole:"eth",
        inputs:[
            {
                hash:"inp3",
                timeStamp:1223,
                value:1200
            }
        ],
        outputs:[
            {
                hash:"out3",
                timeStamp:3441,
                value:2200
            },
            {
                hash:"out5",
                timeStamp:3441,
                value:2200
            }
        ]
    },
    {
        address:"kuft4",
        symbole:"eth",
        inputs:[
            {
                hash:"out5",
                timeStamp:1223,
                value:1200
            },
            {
                hash:"out2",
                timeStamp:1223,
                value:1200
            }
        ],
        outputs:[
            {
                hash:"out4",
                timeStamp:3441,
                value:2200
            }
        ]
    }
]